frontend:
  image: todos:latest
  imagePullPolicy: Never
  port: 3001
  replicas: 1

api:
  image: todos-service:latest
  imagePullPolicy: Never
  port: 8081
  replicas: 1

apiUrl: "http://todos-api:8081"
