apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperbench-operator-manager
  labels:
    {{- include "hyperbench-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperbench-operator-manager
subjects:
  - kind: ServiceAccount
    name: hyperbench-operator
    namespace: {{ .Release.Namespace }}
